version: 2
jobs:
  one:
    environment:
      HEROKU_APP_NAME: vazord-api
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run: cd vazord-backend
      - run: bash .circleci/setup-heroku.sh
      - add_ssh_keys:
          fingerprints:
            - $HEROKU_SSH_FINGERPRINT
      - run:
          name: Deploy Front-End to Heroku
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                    git push --force git@heroku.com:$HEROKU_APP_NAME.git HEAD:refs/heads/master
            fi
  two:
    environment:
      HEROKU_APP_NAME: vazord-client
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run: cd vazord-client
      - run:
          name: Deploy Api to Heroku
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                                git push --force git@heroku.com:$HEROKU_APP_NAME.git HEAD:refs/heads/master
            fi
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two
